# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# - master

pool:
  vmImage: 'windows-2019'

steps:
- task: CondaEnvironment@0
  inputs:
    environmentName: 'py37'
    packageSpecs: 'python=3.7'
    cleanEnvironment: true
- task: CmdLine@2
  inputs:
    script: |
      call activate.bat base
      conda create -y --prefix $(Build.BinariesDirectory)/CTF python=3.7
- task: CmdLine@2
  inputs:
    script: |
      call activate.bat $(Build.BinariesDirectory)/CTF
      $(Build.BinariesDirectory)/CTF/python.exe -m pip install "tensorflow==1.15.*"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.BinariesDirectory)/CTF
      ls *.pyc | rm
      ls *.lib | rm
      ls *.so | rm
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/CTF'
    includeRootFolder: false
    archiveType: '7z'
    sevenZipCompression: 'normal'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ptf-win64-$(Build.BuildId).7z'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
