name: '$(Date:yyyyMMdd)$(Rev:-rr)'

variables:
  archiveName: TensorFlow.tar.xz

trigger: none
# - master

pool:
  vmImage: 'macOS-10.15'

steps:
# Required, see https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=macos#add-conda-to-your-system-path
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add Conda to PATH
- script: |
    conda create -y --prefix $(Build.BinariesDirectory)/CTF python=3.7
    conda init bash
  displayName: Create Conda env
- script: |
    conda activate $(Build.BinariesDirectory)/CTF
    $(Build.BinariesDirectory)/CTF/bin/python -m pip install "tensorflow==$(TensorFlow_Version)" "mlagents-envs==$(MLAgents_Envs_Version)"
  displayName: Install TensorFlow
- task: PowerShell@2
  displayName: Remove unnecessary files
  inputs:
    targetType: 'inline'
    script: |
      Set-Location $(Build.BinariesDirectory)/CTF
      Get-ChildItem *.pyc -Recurse | Remove-Item -Force
      Get-ChildItem *.a -Recurse | Remove-Item -Force
      Get-ChildItem *.o -Recurse | Remove-Item -Force
- task: ArchiveFiles@2
  displayName: Archive Conda env
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/CTF'
    includeRootFolder: false
    archiveType: 'tar'
    tarCompression: 'xz'
    archiveFile: '$(Build.BinariesDirectory)/$(archiveName)'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'custom'
    projects: '**/*.csproj'
    custom: 'pack'
    arguments: '--version-suffix CI-$(Build.BuildNumber) -p:PackagedEnv=$(Build.BinariesDirectory)/$(archiveName) -o $(Build.ArtifactStagingDirectory)'
- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6ea7f709-397d-481c-a895-bf3cf16ec737'
