name: '$(Date:yyyyMMdd)$(Rev:-rr)'

variables:
  archiveName: TensorFlow.tar.xz

trigger: none
# - master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: PowerShell@2
  inputs:
    script: |
      conda activate base
      conda create -y --prefix $(Build.BinariesDirectory)/CTF python=3.7
- task: PowerShell@2
  inputs:
    script: |
      conda activate $(Build.BinariesDirectory)/CTF
      $(Build.BinariesDirectory)/CTF/python -m pip install "tensorflow==1.15.*" mlagents-envs
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.BinariesDirectory)/CTF
      Get-ChildItem *.pyc -Recurse | Remove-Item
      Get-ChildItem *.a -Recurse | Remove-Item
      Get-ChildItem *.o -Recurse | Remove-Item
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/CTF'
    includeRootFolder: false
    archiveType: 'tar'
    tarCompression: 'xz'
    archiveFile: '$(Build.BinariesDirectory)/$(archiveName)'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: '**/*.csproj'
    custom: 'pack'
    arguments: '--version-suffix CI-$(Build.BuildNumber) -p:PackagedEnv=$(Build.BinariesDirectory)/$(archiveName) -o $(Build.ArtifactStagingDirectory)'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6ea7f709-397d-481c-a895-bf3cf16ec737'
