name: '$(Date:yyyyMMdd)$(Rev:-rr)'

trigger: none
# - master

pool:
  vmImage: 'windows-2019'

steps:
- task: NuGetAuthenticate@1
- task: CondaEnvironment@0
  displayName: Ensure Conda is installed
  inputs:
    environmentName: 'py310'
    packageSpecs: 'python=3.10'
    cleanEnvironment: true
- task: CmdLine@2
  displayName: Create Conda env
  inputs:
    script: |
      call activate.bat base
      conda create -y --prefix $(Build.BinariesDirectory)/CTF python=3.10
- task: CmdLine@2
  displayName: Install TensorBoard
  inputs:
    script: |
      call activate.bat $(Build.BinariesDirectory)/CTF
      $(Build.BinariesDirectory)/CTF/python.exe -m pip install "tensorboard==$(TensorBoard_Version)"
- task: PowerShell@2
  displayName: Remove unnecessary files
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.BinariesDirectory)/CTF
      ls *.pyc -Recurse | rm
      ls *.lib -Recurse | rm
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'custom'
    projects: '**/*.csproj'
    custom: 'pack'
    arguments: '--version-suffix CI-$(Build.BuildNumber) -p:PackagedEnv=$(Build.BinariesDirectory)/CTF -o $(Build.ArtifactStagingDirectory)'
- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6ea7f709-397d-481c-a895-bf3cf16ec737'
